# Generated by Django 4.2.7 on 2023-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('UN', 'Unavailable'), ('MA', 'Maintenance'), ('RE', 'Rented')], default='UN', verbose_name='Status'),
        ),
    ]
