# Generated by Django 4.2.7 on 2023-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/img/car_pictures'),
        ),
    ]
