# Generated by Django 4.2.7 on 2023-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_carmaintenance_cost_of_repair_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmaintenance',
            name='status',
            field=models.CharField(choices=[('IR', 'In repair'), ('DO', 'Done'), ('SCH', 'Scheduled')], default='SCH', verbose_name='Status'),
        ),
    ]
