# Generated by Django 4.2.7 on 2023-11-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_carmaintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='car_mileage_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Car mileage at end of car rental'),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='car_mileage_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Car mileage at start of car rental'),
        ),
    ]
