# Generated by Django 4.2.7 on 2023-12-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_alter_carrental_car_mileage_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('main_picture', models.ImageField(blank=True, null=True, upload_to='uploads/img/news')),
                ('slug', models.SlugField(max_length=140)),
            ],
        ),
    ]
