# Generated by Django 4.2.7 on 2023-12-09 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
