# Generated by Django 4.2.7 on 2023-12-14 10:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_rental', '0010_rentalextra_rentalprotection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='car_mileage_change',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='car_mileage_end',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='car_mileage_start',
        ),
        migrations.AddField(
            model_name='car',
            name='day_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=19, verbose_name='Cost of one day rental'),
        ),
        migrations.AddField(
            model_name='car',
            name='day_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'Polish Zloty')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='carrental',
            name='extra',
            field=models.ManyToManyField(to='car_rental.rentalextra', verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental.rentalprotection', verbose_name='Protection'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='total_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=19, verbose_name='Cost of rental'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='total_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PLN', 'Polish Zloty')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='RentalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, max_length=255, verbose_name='Building number')),
                ('post_code', models.CharField(blank=True, max_length=16, verbose_name='Post code')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rental address',
                'verbose_name_plural': 'Rental addresses',
            },
        ),
        migrations.AddField(
            model_name='carrental',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental.rentaladdress', verbose_name='User'),
        ),
    ]
