# Generated by Django 4.2.7 on 2023-12-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0011_remove_carrental_car_mileage_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.AlterField(
            model_name='carrental',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_rental.rentaladdress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='rentaladdress',
            name='building_number',
            field=models.CharField(max_length=255, verbose_name='Building number'),
        ),
        migrations.AlterField(
            model_name='rentaladdress',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='rentaladdress',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='rentaladdress',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='rentaladdress',
            name='post_code',
            field=models.CharField(max_length=16, verbose_name='Post code'),
        ),
    ]
