# Generated by Django 4.2.7 on 2023-12-18 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_rental', '0012_remove_car_mileage_alter_carrental_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AC', 'Accident'), ('BR', 'Breakdown'), ('QU', 'Question'), ('CO', 'Complaint')], default='QU')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NE', 'New'), ('CL', 'Closed')], default='NE')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
            },
        ),
    ]
