# Generated by Django 4.2.7 on 2023-12-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_rental', '0013_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('AC', 'Accident'), ('BR', 'Breakdown'), ('QU', 'Question'), ('CO', 'Complaint')], default='QU', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('CL', 'Closed')], default='NE', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CarLongTermRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date of car rental')),
                ('number_of_months', models.PositiveIntegerField(verbose_name='Number of months')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('NE', 'New'), ('IP', 'In progress'), ('CL', 'Closed')], default='NE', verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Long term rental',
                'verbose_name_plural': 'Long term rentals',
            },
        ),
    ]
