# Generated by Django 4.2.7 on 2023-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_alter_contactmessage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='status',
            field=models.CharField(choices=[('RS', 'Reserved'), ('RE', 'Rented'), ('CL', 'Closed'), ('CA', 'Cancelled')], default='RS', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='carlongtermrental',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('IP', 'In progress'), ('CL', 'Closed'), ('CA', 'Cancelled')], default='NE', verbose_name='Status'),
        ),
    ]
