# Generated by Django 4.2.7 on 2023-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0015_carrental_status_alter_carlongtermrental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='extra',
            field=models.ManyToManyField(blank=True, null=True, to='car_rental.rentalextra', verbose_name='Extra'),
        ),
    ]
