# Generated by Django 4.2.7 on 2023-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_alter_carrental_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='extra',
            field=models.ManyToManyField(blank=True, to='car_rental.rentalextra', verbose_name='Extra'),
        ),
    ]
