# Generated by Django 4.2.7 on 2023-12-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_delete_carlongtermrental'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 28, 10, 22, 7, 866234, tzinfo=datetime.timezone.utc), verbose_name='Date of contact message creation'),
            preserve_default=False,
        ),
    ]
