# Generated by Django 4.2.7 on 2024-01-03 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0019_contactmessage_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/img/car_pictures', verbose_name='Car picture'),
        ),
        migrations.AlterField(
            model_name='news',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Add date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/img/news', verbose_name='Main picture'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
