# Generated by Django 4.2.7 on 2024-01-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0020_alter_car_car_picture_alter_news_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaladdress',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
    ]
