# Generated by Django 4.2.7 on 2024-01-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0022_alter_carrental_end_date_alter_carrental_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalprotection',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='rentalprotection',
            name='penalty_currency',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_capacity'
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(blank=True, verbose_name='Engine capacity [l]', default=0),
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_power',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, verbose_name='Engine power [hp]', default=0),
        ),
    ]
