# Generated by Django 4.2.7 on 2024-01-14 12:26

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0023_remove_rentalprotection_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_bleach.models.BleachField(verbose_name='Description'),
        ),
    ]
